export const cityOptions = [
    { text: '臺北市', code: 'Taipei' },
    { text: '新北市', code: 'NewTaipei' },
    { text: '桃園市', code: 'Taoyuan' },
    { text: '臺中市', code: 'Taichung' },
    { text: '臺南市', code: 'Tainan' },
    { text: '高雄市', code: 'Kaohsiung' },
    { text: '基隆市', code: 'Keelung' },
    { text: '新竹市', code: 'Hsinchu' },
    { text: '新竹縣', code: 'HsinchuCounty' },
    { text: '苗栗縣', code: 'MiaoliCounty' },
    { text: '彰化縣', code: 'ChanghuaCounty' },
    { text: '南投縣', code: 'NantouCounty' },
    { text: '雲林縣', code: 'YunlinCounty' },
    { text: '嘉義縣', code: 'ChiayiCounty' },
    { text: '嘉義市', code: 'Chiayi' },
    { text: '屏東縣', code: 'PingtungCounty' },
    { text: '宜蘭縣', code: 'YilanCounty' },
    { text: '花蓮縣', code: 'HualienCounty' },
    { text: '臺東縣', code: 'TaitungCounty' },
    { text: '金門縣', code: 'KinmenCounty' },
    { text: '澎湖縣', code: 'PenghuCounty' },
    { text: '連江縣', code: 'LienchiangCounty' },
];